# -*- coding: utf-8 -*-
"""datverseipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OuAJts8LTMQUR3DTDLB7P2pbfjcyBFG0
"""

!pip install streamlit pyngrok

!streamlit run app1.py &>/dev/null&

!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared-linux-amd64

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# # ---------------- PAGE CONFIG ----------------
# st.set_page_config(
#     page_title="Upsprout 🌱",
#     page_icon="🤖",
#     layout="centered"
# )
# 
# # ---------------- GLOBAL STYLES ----------------
# st.markdown("""
# <style>
# [data-testid="stApp"] {
#     background: radial-gradient(circle at top left, #ECFEFF, #F0FDF4);
# }
# footer {visibility: hidden;}
# 
# .hero-container {
#     display: flex;
#     align-items: center;
#     justify-content: space-between;
#     background: linear-gradient(135deg, #34D399, #0EA5E9);
#     padding: 3rem;
#     border-radius: 28px;
#     color: white;
#     margin-bottom: 2.5rem;
# }
# .hero-text h1 {
#     font-size: 44px;
#     font-weight: 800;
# }
# .hero-text p {
#     font-size: 18px;
# }
# .card {
#     background: white;
#     padding: 1.8rem;
#     border-radius: 22px;
#     box-shadow: 0 14px 35px rgba(0,0,0,0.08);
#     margin-bottom: 1.6rem;
# }
# .feature-card {
#     background: white;
#     padding: 1.4rem;
#     border-radius: 20px;
#     box-shadow: 0 12px 28px rgba(0,0,0,0.07);
#     text-align: center;
# }
# .stButton > button {
#     background: linear-gradient(135deg, #0EA5E9, #22C55E);
#     color: white;
#     border-radius: 16px;
#     font-weight: 600;
# }
# h2, h3 { color: #15803D; }
# </style>
# """, unsafe_allow_html=True)
# 
# # ---------------- SESSION STATE ----------------
# for key in ["analysis_result", "growth_plan", "pitch", "ready_status", "logged_in", "users", "auth_mode"]:
#     if key not in st.session_state:
#         st.session_state[key] = "" if key not in ["users", "auth_mode"] else {}  # users dict & auth_mode
# 
# # ---------------- LOGIN / CREATE ACCOUNT ----------------
# st.header("🔑 Welcome to Upsprout")
# st.write("Please login or create a new account to continue.")
# 
# c1, c2 = st.columns(2)
# with c1:
#     if st.button("Login"):
#         st.session_state.auth_mode = "login"
# with c2:
#     if st.button("Create an Account"):
#         st.session_state.auth_mode = "register"
# 
# if not st.session_state.get("logged_in") and st.session_state.get("auth_mode"):
#     username = st.text_input("Username")
#     password = st.text_input("Password", type="password")
# 
#     if st.button("Submit"):
#         if st.session_state.auth_mode == "register":
#             if username in st.session_state.users:
#                 st.error("Username already exists! Try logging in.")
#             elif username == "" or password == "":
#                 st.warning("Please enter both username and password.")
#             else:
#                 st.session_state.users[username] = password
#                 st.success(f"Account created for {username}! You can now login.")
#         elif st.session_state.auth_mode == "login":
#             if username in st.session_state.users and st.session_state.users[username] == password:
#                 st.session_state.logged_in = username
#                 st.success(f"Welcome back, {username}!")
#             else:
#                 st.error("Invalid username or password!")
# 
# # ---------------- MAIN APP ----------------
# if st.session_state.get("logged_in"):
#     st.success(f"👋 Logged in as {st.session_state.logged_in}")
#     st.markdown("---")
# 
#     # ---------------- HERO ----------------
#     st.markdown("""
#     <div class="hero-container">
#         <div class="hero-text">
#             <h1>Upsprout 🌱</h1>
#             <p>Your AI-powered growth companion for small businesses</p>
#         </div>
#     </div>
#     """, unsafe_allow_html=True)
# 
#     st.info("🤖 Tell me about your business — I’ll give **relevant, practical guidance**, not generic advice.")
# 
#     # ---------------- INPUT ----------------
#     st.markdown("<div class='card'>", unsafe_allow_html=True)
#     st.header("📌 Business Details")
# 
#     business_type = st.text_input("🏪 Describe your business")
#     annual_budget = st.number_input("💰 Annual Marketing Budget", min_value=0, step=1000)
#     time_per_week = st.slider("⏱ Time per week (hours)", 1, 15)
#     goal = st.selectbox("🎯 Primary Goal", ["Visibility", "Sales", "Expansion"])
# 
#     # ---------------- PLATFORM SELECTION ----------------
#     all_platforms = ["Instagram", "WhatsApp", "Facebook", "Swiggy", "Zomato",
#                      "Etsy", "IndiaMART", "UrbanCompany", "TradeIndia",
#                      "LinkedIn", "Upwork", "Twitter"]
# 
#     selected_platforms = st.multiselect("📱 Select Platforms you want to focus on", all_platforms)
#     st.markdown("</div>", unsafe_allow_html=True)
# 
#     # ---------------- CORE LOGIC ----------------
#     def classify_budget(budget):
#         if budget < 50000: return "Low"
#         elif budget < 200000: return "Medium"
#         return "High"
# 
#     def readiness_check(budget_level, time):
#         score = (40 if budget_level != "Low" else 10) + (40 if time >= 4 else 10) + 20
#         return score >= 70, score
# 
#     def classify_business(text):
#         t = text.lower()
#         if any(k in t for k in ["restaurant", "cafe", "bakery", "food"]):
#             return "Food & Beverage"
#         if any(k in t for k in ["salon", "spa", "repair", "service", "plumber"]):
#             return "Local Service"
#         if any(k in t for k in ["textile", "handmade", "product", "shop"]):
#             return "Product Business"
#         if any(k in t for k in ["b2b", "manufacturer", "supplier", "wholesale"]):
#             return "B2B Business"
#         if any(k in t for k in ["coach", "trainer", "consultant", "freelancer"]):
#             return "Professional Service"
#         if any(k in t for k in ["startup", "tech", "app", "software"]):
#             return "Startup / Tech"
#         return "General Business"
# 
#     # ---------------- BUSINESS STRATEGY ----------------
#     BUSINESS_STRATEGY = {
#         "Food & Beverage": {
#             "platforms": ["Instagram", "Swiggy", "Zomato"],
#             "actions": [
#                 "Optimize menu visuals",
#                 "Peak-hour offers",
#                 "Collect reviews aggressively",
#                 "Collaborate with local influencers"
#             ],
#             "funding": {
#                 "Low": ["Crowdfunding for local food lovers", "Small restaurant grants", "Prepaid meal packages"],
#                 "Medium": ["Partner with local investors", "Bank small business loans"],
#                 "High": ["Expand to multiple outlets", "Attract angel investors"]
#             }
#         },
#         "Local Service": {
#             "platforms": ["WhatsApp", "Instagram"],
#             "actions": [
#                 "Before-after photos",
#                 "Fast response guarantee",
#                 "Customer testimonials",
#                 "Referral reward programs"
#             ],
#             "funding": {
#                 "Low": ["Offer service vouchers in advance", "Join micro-grant programs"],
#                 "Medium": ["Local business loans", "Small service investors"],
#                 "High": ["Expand to multiple locations", "Franchise model"]
#             }
#         },
#         "Product Business": {
#             "platforms": ["Instagram", "Etsy", "Facebook Marketplace"],
#             "actions": [
#                 "Storytelling reels",
#                 "Packaging upgrade",
#                 "Limited edition drops",
#                 "Collaborate with micro-influencers"
#             ],
#             "funding": {
#                 "Low": ["Crowdfunding campaigns", "Pre-order sales"],
#                 "Medium": ["Local business loans", "Angel investors"],
#                 "High": ["Series A funding", "E-commerce expansion"]
#             }
#         },
#         "B2B Business": {
#             "platforms": ["IndiaMART", "TradeIndia", "LinkedIn"],
#             "actions": [
#                 "Professional catalog",
#                 "Fast quotation",
#                 "Bulk pricing clarity",
#                 "Attend trade shows"
#             ],
#             "funding": {
#                 "Low": ["Invoice factoring", "Advance customer payments"],
#                 "Medium": ["Bank loans", "Private equity small rounds"],
#                 "High": ["Venture capital", "Strategic partnerships"]
#             }
#         },
#         "Professional Service": {
#             "platforms": ["LinkedIn", "Instagram", "Upwork"],
#             "actions": [
#                 "Authority content",
#                 "Case studies",
#                 "Free audits",
#                 "Offer webinars or workshops"
#             ],
#             "funding": {
#                 "Low": ["Service prepayments", "Small business grants"],
#                 "Medium": ["Professional service loans", "Partner collaborations"],
#                 "High": ["Premium packages", "Investor-backed scaling"]
#             }
#         },
#         "Startup / Tech": {
#             "platforms": ["LinkedIn", "Product Hunt", "Twitter"],
#             "actions": [
#                 "MVP traction",
#                 "User testimonials",
#                 "Clear problem-solution fit",
#                 "Engage early adopters"
#             ],
#             "funding": {
#                 "Low": ["Friends & family funding", "Startup bootstrapping", "Incubator programs"],
#                 "Medium": ["Angel investors", "Seed funding rounds"],
#                 "High": ["Venture capital", "Series A/B funding"]
#             }
#         },
#         "General Business": {
#             "platforms": ["Instagram", "WhatsApp"],
#             "actions": [
#                 "Consistent posting",
#                 "Clear value proposition",
#                 "Local engagement",
#                 "Participate in community events"
#             ],
#             "funding": {
#                 "Low": ["Bootstrapping", "Crowdfunding", "Micro-grants"],
#                 "Medium": ["Local investors", "Bank loans"],
#                 "High": ["Expand operations", "Attract angel investors"]
#             }
#         }
#     }
# 
#     # ---------------- ANALYSIS ----------------
#     def analyze():
#         category = classify_business(business_type)
#         budget_level = classify_budget(annual_budget)
#         ready, score = readiness_check(budget_level, time_per_week)
#         st.session_state.ready_status = ready
# 
#         strategy = BUSINESS_STRATEGY[category]
# 
#         # Use user-selected platforms
#         platforms_to_show = selected_platforms if selected_platforms else strategy["platforms"]
# 
#         st.session_state.analysis_result = f"""
# ### 📊 Business Analysis
# 
# **Detected Category:** {category}
# **Budget:** {budget_level}
# **Time:** {time_per_week} hrs/week
# **Goal:** {goal}
# 
# ---
# 
# ### 📱 Platforms you selected
# {", ".join(platforms_to_show)}
# 
# ---
# 
# ### 🧠 Key Actions
# {"".join([f"- {a}\n" for a in strategy["actions"]])}
# 
# ---
# 
# ### 🚦 Readiness
# {"✅ READY" if ready else "❌ NEEDS IMPROVEMENT"} ({score}/100)
# """
# 
#     # ---------------- GROWTH PLAN ----------------
#     def generate_plan():
#         category = classify_business(business_type)
#         actions = BUSINESS_STRATEGY[category]["actions"]
#         st.session_state.growth_plan = f"""
# ### 📅 7-Day Growth Plan
# {"".join([f"- Day focus: {a}\n" for a in actions])}
# """
# 
#     # ---------------- FUNDRAISING ----------------
#     def generate_pitch():
#         category = classify_business(business_type)
#         budget_level = classify_budget(annual_budget)
#         funding_options = BUSINESS_STRATEGY[category]["funding"][budget_level]
# 
#         friendly_funding = []
#         for f in funding_options:
#             f_lower = f.lower()
#             if "bootstrapping" in f_lower or "prepayments" in f_lower:
#                 friendly_funding.append("💰 Bootstrap — use your own savings wisely, start small, reinvest profits")
#             elif "crowdfunding" in f_lower or "campaign" in f_lower:
#                 friendly_funding.append("🌐 Crowdfunding — ask your community or online supporters to fund small portions")
#             elif "grant" in f_lower or "micro-grant" in f_lower:
#                 friendly_funding.append("🎁 Micro-grants — apply for small free funds from organizations or local programs")
#             else:
#                 friendly_funding.append(f)
# 
#         if st.session_state.ready_status:
#             st.session_state.pitch = f"""
# ### 🤝 Fundraising Improvement (Growth Stage)
# 
# **Best Funding Paths:**
# {', '.join(friendly_funding)}
# 
# #### Improve Fundability:
# - Track weekly growth metrics
# - Document testimonials
# - Show 30-day traction
# - Prepare 1-page business snapshot
# """
#         else:
#             st.session_state.pitch = f"""
# ### 🤝 Fundraising Improvement (Pre-Stage)
# 
# **Current Focus:**
# {', '.join(friendly_funding)}
# 
# #### Fix Before Raising:
# - Stabilize revenue
# - Increase repeat customers
# - Validate demand
# - Implement low-cost growth actions
# """
# 
#     # ---------------- BUTTONS ----------------
#     st.header("🚀 Actions")
#     c1, c2, c3 = st.columns(3)
# 
#     with c1:
#         if st.button("🔍 Analyze"): analyze()
#     with c2:
#         if st.button("📈 Growth Plan"): generate_plan()
#     with c3:
#         if st.button("🤝 Fundraising"): generate_pitch()
# 
#     # ---------------- OUTPUT ----------------
#     st.header("📤 Output")
# 
#     for item in ["analysis_result", "growth_plan", "pitch"]:
#         if st.session_state[item]:
#             st.markdown("<div class='card'>", unsafe_allow_html=True)
#             st.markdown(st.session_state[item])
#             st.markdown("</div>", unsafe_allow_html=True)
#

!ls

!streamlit run app.py & ./cloudflared-linux-amd64 tunnel --url http://localhost:8501