# -*- coding: utf-8 -*-
"""datverse1ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OuAJts8LTMQUR3DTDLB7P2pbfjcyBFG0
"""

!pip install streamlit pyngrok

!streamlit run app1.py &>/dev/null&

!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared-linux-amd64

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# # ================= PAGE CONFIG =================
# st.set_page_config(
#     page_title="Upsprout 🌱",
#     page_icon="🤖",
#     layout="centered"
# )
# 
# # ================= STYLES =================
# st.markdown("""
# <style>
# [data-testid="stApp"] {
#     background: radial-gradient(circle at top left, #ECFEFF, #F0FDF4);
# }
# footer {visibility: hidden;}
# .card {
#     background: white;
#     padding: 1.8rem;
#     border-radius: 22px;
#     box-shadow: 0 14px 35px rgba(0,0,0,0.08);
#     margin-bottom: 1.6rem;
# }
# .hero {
#     background: linear-gradient(135deg, #34D399, #0EA5E9);
#     padding: 3rem;
#     border-radius: 28px;
#     color: white;
#     margin-bottom: 2rem;
# }
# .stButton > button {
#     background: linear-gradient(135deg, #0EA5E9, #22C55E);
#     color: white;
#     border-radius: 16px;
#     font-weight: 600;
# }
# </style>
# """, unsafe_allow_html=True)
# 
# # ================= SESSION STATE =================
# defaults = {
#     "users": {},
#     "logged_in": False,
#     "current_user": "",
#     "analysis": "",
#     "plan": "",
#     "pitch": "",
#     "ready": False,
#     "score": 0
# }
# for k, v in defaults.items():
#     if k not in st.session_state:
#         st.session_state[k] = v
# 
# # =================================================
# # 🔐 AUTH PAGE (ONE PAGE ONLY)
# # =================================================
# if not st.session_state.logged_in:
# 
#     st.markdown("<div class='card'>", unsafe_allow_html=True)
#     st.header("🔐 Welcome to Upsprout")
# 
#     mode = st.radio("Choose action", ["Login", "Register"])
#     username = st.text_input("Username")
#     password = st.text_input("Password", type="password")
# 
#     if st.button("Continue"):
#         if mode == "Register":
#             if not username or not password:
#                 st.warning("Please fill all fields.")
#             elif username in st.session_state.users:
#                 st.error("User already exists.")
#             else:
#                 st.session_state.users[username] = password
#                 st.success("Account created. Please login.")
# 
#         else:  # Login
#             if st.session_state.users.get(username) == password:
#                 st.session_state.logged_in = True
#                 st.session_state.current_user = username
#                 st.rerun()
#             else:
#                 st.error("Invalid credentials")
# 
#     st.markdown("</div>", unsafe_allow_html=True)
# 
# # =================================================
# # 🌱 MAIN UPSPROUT APP
# # =================================================
# else:
# 
#     st.markdown(f"""
#     <div class="hero">
#         <h1>Upsprout 🌱</h1>
#         <p>Welcome, <b>{st.session_state.current_user}</b> 👋<br>
#         AI-powered, resource-aware business growth assistant</p>
#     </div>
#     """, unsafe_allow_html=True)
# 
#     # ================= INPUT =================
#     st.markdown("<div class='card'>", unsafe_allow_html=True)
#     business = st.text_input("🏪 Describe your business")
#     budget = st.number_input("💰 Annual marketing budget", min_value=0, step=1000)
#     time = st.slider("⏱ Time available per week (hours)", 1, 15)
#     goal = st.selectbox("🎯 Primary goal", ["Visibility", "Sales", "Expansion"])
#     platforms = st.multiselect(
#         "📱 Platforms you want to use",
#         ["Instagram", "WhatsApp", "YouTube", "Swiggy", "Zomato",
#          "Etsy", "IndiaMART", "TradeIndia", "LinkedIn"]
#     )
#     st.markdown("</div>", unsafe_allow_html=True)
# 
#     # ================= HELPERS =================
#     def budget_level(b):
#         if b < 50000: return "Low"
#         if b < 200000: return "Medium"
#         return "High"
# 
#     def readiness(b_lvl, t):
#         score = (30 if b_lvl != "Low" else 10) + (40 if t >= 4 else 10) + 20
#         return score >= 70, score
# 
#     # ================= ANALYZE (NOVELTIES 6,1,2,3) =================
#     def analyze():
#         b_lvl = budget_level(budget)
#         ready, score = readiness(b_lvl, time)
#         st.session_state.ready = ready
#         st.session_state.score = score
# 
#         base = f"""
# ### 📊 Business Analysis
# **Budget Level:** {b_lvl}
# **Time Available:** {time} hrs/week
# **Goal:** {goal}
# 
# ### 📱 Platforms
# {", ".join(platforms) if platforms else "Focus on one strong platform"}
# """
# 
#         if not ready:
#             st.session_state.analysis = base + f"""
# ---
# ### 🚦 Readiness Status: NOT READY ({score}/100)
# 
# ### 🔧 How to Improve (Guidance Mode)
# • Increase effort to **4+ hrs/week**
# • Use **pre-orders / referrals** to expand budget
# • Focus on **one platform only**
# • Be consistent for **2 weeks**
# 
# 🤖 *Upsprout will unlock advanced insights once ready.*
# """
#         else:
#             st.session_state.analysis = base + f"""
# ---
# ### 🚦 Readiness Status: READY ({score}/100)
# 
# ### ✅ AI Confidence (Novelty 1)
# Confidence Level: **HIGH (85%)**
# 
# ### ⚖ Trade-off Awareness (Novelty 2)
# • Faster growth → higher effort
# • Organic growth → safer, slower ROI
# 
# ### 🧪 Micro-Experiment (Novelty 3)
# **Try:** 2 high-quality posts this week
# **Measure:** Inquiries & saves
# **Review after:** 7 days
# 
# 🤖 *Proceed with controlled scaling.*
# """
# 
#     # ================= PLAN =================
#     def plan():
#         st.session_state.plan = """
# ### 📅 7-Day Growth Plan
# • 2 platform-specific posts
# • 1 engagement post
# • Track inquiries daily
# """
# 
#     # ================= FUNDING =================
#     def fund():
#         if st.session_state.ready:
#             st.session_state.pitch = """
# ### 🤝 Fundraising (Growth Stage)
# • Approach micro-investors
# • Use engagement metrics
# • Partner with similar businesses
# """
#         else:
#             st.session_state.pitch = """
# ### 🤝 Fundraising (Bootstrap Stage)
# • Pre-orders & referrals
# • Community selling
# • Barter-based partnerships
# """
# 
#     # ================= ACTIONS =================
#     c1, c2, c3 = st.columns(3)
#     with c1:
#         if st.button("🔍 Analyze"): analyze()
#     with c2:
#         if st.button("📈 Growth Plan"): plan()
#     with c3:
#         if st.button("🤝 Fundraising"): fund()
# 
#     # ================= OUTPUT =================
#     st.header("📤 Upsprout Output")
#     for section in ["analysis", "plan", "pitch"]:
#         if st.session_state[section]:
#             st.markdown("<div class='card'>", unsafe_allow_html=True)
#             st.markdown(st.session_state[section])
#             st.markdown("</div>", unsafe_allow_html=True)
# 
#     # ================= LOGOUT =================
#     if st.button("🚪 Logout"):
#         st.session_state.logged_in = False
#         st.session_state.current_user = ""
#         st.rerun()

!ls

!streamlit run app.py & ./cloudflared-linux-amd64 tunnel --url http://localhost:8501