# -*- coding: utf-8 -*-
"""DataVerse2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JYux2wTNqZ_MAG482IM-VaER3pU3yFol
"""

!pip install streamlit pyngrok

!streamlit run app1.py &>/dev/null&

!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared-linux-amd64

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# # ---------------- PAGE CONFIG ----------------
# st.set_page_config(
#     page_title="Upsprout 🌱",
#     page_icon="🤖",
#     layout="centered"
# )
# 
# # ---------------- GLOBAL STYLES ----------------
# st.markdown("""
# <style>
# [data-testid="stApp"] {
#     background: radial-gradient(circle at top left, #ECFEFF, #F0FDF4);
# }
# footer {visibility: hidden;}
# 
# .hero-container {
#     display: flex;
#     align-items: center;
#     justify-content: space-between;
#     background: linear-gradient(135deg, #34D399, #0EA5E9);
#     padding: 3rem;
#     border-radius: 28px;
#     color: white;
#     margin-bottom: 2.5rem;
# }
# .hero-text h1 {
#     font-size: 44px;
#     font-weight: 800;
# }
# .hero-text p {
#     font-size: 18px;
# }
# .card {
#     background: white;
#     padding: 1.8rem;
#     border-radius: 22px;
#     box-shadow: 0 14px 35px rgba(0,0,0,0.08);
#     margin-bottom: 1.6rem;
# }
# .feature-card {
#     background: white;
#     padding: 1.4rem;
#     border-radius: 20px;
#     box-shadow: 0 12px 28px rgba(0,0,0,0.07);
#     text-align: center;
# }
# .stButton > button {
#     background: linear-gradient(135deg, #0EA5E9, #22C55E);
#     color: white;
#     border-radius: 16px;
#     font-weight: 600;
# }
# h2, h3 { color: #15803D; }
# </style>
# """, unsafe_allow_html=True)
# 
# # ---------------- HERO ----------------
# st.markdown("""
# <div class="hero-container">
#     <div class="hero-text">
#         <h1>Upsprout 🌱</h1>
#         <p>Your AI-powered growth companion for small businesses</p>
#     </div>
# </div>
# """, unsafe_allow_html=True)
# 
# st.info("🤖 Tell me about your business — I’ll give **relevant, practical guidance**, not generic advice.")
# 
# # ---------------- SESSION STATE ----------------
# for key in ["analysis_result", "growth_plan", "pitch", "ready_status"]:
#     if key not in st.session_state:
#         st.session_state[key] = ""
# 
# # ---------------- INPUT ----------------
# st.markdown("<div class='card'>", unsafe_allow_html=True)
# st.header("📌 Business Details")
# 
# business_type = st.text_input("🏪 Describe your business")
# annual_budget = st.number_input("💰 Annual Marketing Budget", min_value=0, step=1000)
# time_per_week = st.slider("⏱ Time per week (hours)", 1, 15)
# goal = st.selectbox("🎯 Primary Goal", ["Visibility", "Sales", "Expansion"])
# st.markdown("</div>", unsafe_allow_html=True)
# 
# # ---------------- CORE LOGIC ----------------
# def classify_budget(budget):
#     if budget < 50000: return "Low"
#     elif budget < 200000: return "Medium"
#     return "High"
# 
# def readiness_check(budget_level, time):
#     score = (40 if budget_level != "Low" else 10) + (40 if time >= 4 else 10) + 20
#     return score >= 70, score
# 
# def classify_business(text):
#     t = text.lower()
#     if any(k in t for k in ["restaurant", "cafe", "bakery", "food"]):
#         return "Food & Beverage"
#     if any(k in t for k in ["salon", "spa", "repair", "service", "plumber"]):
#         return "Local Service"
#     if any(k in t for k in ["textile", "handmade", "product", "shop"]):
#         return "Product Business"
#     if any(k in t for k in ["b2b", "manufacturer", "supplier", "wholesale"]):
#         return "B2B Business"
#     if any(k in t for k in ["coach", "trainer", "consultant", "freelancer"]):
#         return "Professional Service"
#     if any(k in t for k in ["startup", "tech", "app", "software"]):
#         return "Startup / Tech"
#     return "General Business"
# 
# BUSINESS_STRATEGY = {
#     "Food & Beverage": {
#         "platforms": ["Instagram", "Swiggy", "Zomato"],
#         "actions": [
#             "Optimize menu visuals",
#             "Peak-hour offers",
#             "Collect reviews aggressively"
#         ],
#         "funding": "Revenue reinvestment + local partners"
#     },
#     "Local Service": {
#         "platforms": ["WhatsApp", "Instagram"],
#         "actions": [
#             "Before-after photos",
#             "Fast response guarantee",
#             "Customer testimonials"
#         ],
#         "funding": "Advance bookings + referrals"
#     },
#     "Product Business": {
#         "platforms": ["Instagram", "Etsy"],
#         "actions": [
#             "Storytelling reels",
#             "Packaging upgrade",
#             "Limited edition drops"
#         ],
#         "funding": "Pre-orders + micro-investors"
#     },
#     "B2B Business": {
#         "platforms": ["IndiaMART", "TradeIndia"],
#         "actions": [
#             "Professional catalog",
#             "Fast quotation",
#             "Bulk pricing clarity"
#         ],
#         "funding": "Distributor advances"
#     },
#     "Professional Service": {
#         "platforms": ["LinkedIn", "Instagram"],
#         "actions": [
#             "Authority content",
#             "Case studies",
#             "Free audits"
#         ],
#         "funding": "Retainers + premium packages"
#     },
#     "Startup / Tech": {
#         "platforms": ["LinkedIn", "Product Hunt"],
#         "actions": [
#             "MVP traction",
#             "User testimonials",
#             "Clear problem-solution fit"
#         ],
#         "funding": "Angel investors + accelerators"
#     },
#     "General Business": {
#         "platforms": ["Instagram", "WhatsApp"],
#         "actions": [
#             "Consistent posting",
#             "Clear value proposition",
#             "Local engagement"
#         ],
#         "funding": "Bootstrapping"
#     }
# }
# 
# # ---------------- ANALYSIS ----------------
# def analyze():
#     category = classify_business(business_type)
#     budget_level = classify_budget(annual_budget)
#     ready, score = readiness_check(budget_level, time_per_week)
#     st.session_state.ready_status = ready
# 
#     strategy = BUSINESS_STRATEGY[category]
# 
#     st.session_state.analysis_result = f"""
# ### 📊 Business Analysis
# 
# **Detected Category:** {category}
# **Budget:** {budget_level}
# **Time:** {time_per_week} hrs/week
# **Goal:** {goal}
# 
# ---
# 
# ### 📱 Recommended Platforms
# {", ".join(strategy["platforms"])}
# 
# ---
# 
# ### 🧠 Key Actions
# {"".join([f"- {a}\n" for a in strategy["actions"]])}
# 
# ---
# 
# ### 🚦 Readiness
# {"✅ READY" if ready else "❌ NEEDS IMPROVEMENT"} ({score}/100)
# """
# 
# # ---------------- GROWTH PLAN ----------------
# def generate_plan():
#     category = classify_business(business_type)
#     actions = BUSINESS_STRATEGY[category]["actions"]
#     st.session_state.growth_plan = f"""
# ### 📅 7-Day Growth Plan
# {"".join([f"- Day focus: {a}\n" for a in actions])}
# """
# 
# # ---------------- FUNDRAISING (IMPROVED) ----------------
# def generate_pitch():
#     category = classify_business(business_type)
#     funding = BUSINESS_STRATEGY[category]["funding"]
# 
#     if st.session_state.ready_status:
#         st.session_state.pitch = f"""
# ### 🤝 Fundraising Improvement (Growth Stage)
# 
# **Best Funding Path:** {funding}
# 
# #### Improve Fundability:
# - Track weekly growth metrics
# - Document testimonials
# - Show 30-day traction
# - Prepare 1-page business snapshot
# """
#     else:
#         st.session_state.pitch = f"""
# ### 🤝 Fundraising Improvement (Pre-Stage)
# 
# **Current Focus:** {funding}
# 
# #### Fix Before Raising:
# - Stabilize revenue
# - Increase repeat customers
# - Validate demand
# """
# 
# # ---------------- BUTTONS ----------------
# st.header("🚀 Actions")
# c1, c2, c3 = st.columns(3)
# 
# with c1:
#     if st.button("🔍 Analyze"): analyze()
# with c2:
#     if st.button("📈 Growth Plan"): generate_plan()
# with c3:
#     if st.button("🤝 Fundraising"): generate_pitch()
# 
# # ---------------- OUTPUT ----------------
# st.header("📤 Output")
# 
# for item in ["analysis_result", "growth_plan", "pitch"]:
#     if st.session_state[item]:
#         st.markdown("<div class='card'>", unsafe_allow_html=True)
#         st.markdown(st.session_state[item])
#         st.markdown("</div>", unsafe_allow_html=True)
#

!ls

!streamlit run app.py & ./cloudflared-linux-amd64 tunnel --url http://localhost:8501