# -*- coding: utf-8 -*-
"""hackathon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xhrt9_y8uIZiBq_oRlLW-g_AB7fHqzWY
"""

!pip install streamlit pyngrok

!pip install -q streamlit

!streamlit run app1.py &>/dev/null&

!streamlit run app1.py --server.port 8501 --server.address 0.0.0.0

!ls

!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared-linux-amd64

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app1.py
# import streamlit as st
# 
# # ---------------- PAGE CONFIG ----------------
# st.set_page_config(
#     page_title="Upsprout 🤖🌱",
#     page_icon="🌱",
#     layout="wide"
# )
# 
# # ---------------- STYLES ----------------
# st.markdown("""
# <style>
# [data-testid="stApp"] {
#     background: linear-gradient(135deg, #e8fdf5, #f4f9ff);
# }
# 
# /* HERO */
# .hero {
#     display: flex;
#     justify-content: space-between;
#     align-items: center;
#     padding: 2rem 3rem;
# }
# .hero h1 {
#     font-size: 46px;
#     color: #2e8b57;
# }
# .hero p {
#     font-size: 18px;
#     color: #4f6f52;
# }
# .robot {
#     font-size: 120px;
#     animation: float 3s ease-in-out infinite;
# }
# @keyframes float {
#     0% { transform: translateY(0px); }
#     50% { transform: translateY(-10px); }
#     100% { transform: translateY(0px); }
# }
# 
# /* CARDS */
# .card {
#     background: white;
#     padding: 1.6rem;
#     border-radius: 18px;
#     box-shadow: 0 8px 22px rgba(0,0,0,0.06);
#     margin-bottom: 1.5rem;
# }
# 
# /* ACTION CARDS */
# .action-card {
#     background: #f8fffb;
#     border-radius: 18px;
#     padding: 1.4rem;
#     text-align: center;
#     border: 2px solid #e0f2ea;
#     box-shadow: 0 6px 16px rgba(0,0,0,0.05);
#     transition: all 0.25s ease;
# }
# .action-card:hover {
#     transform: translateY(-6px);
#     background: #ecfff7;
# }
# .action-icon {
#     font-size: 44px;
# }
# .action-title {
#     font-size: 18px;
#     font-weight: 600;
#     margin-top: 8px;
# }
# </style>
# """, unsafe_allow_html=True)
# 
# # ---------------- HERO SECTION ----------------
# st.markdown("""
# <div class="hero">
#     <div>
#         <h1>Upsprout 🌱</h1>
#         <p>Your AI assistant for smart, sustainable business growth</p>
#     </div>
#     <div class="robot">🤖</div>
# </div>
# """, unsafe_allow_html=True)
# 
# # ---------------- SESSION STATE ----------------
# for key in ["analysis", "plan", "pitch", "ready"]:
#     if key not in st.session_state:
#         st.session_state[key] = ""
# 
# # ---------------- INPUT SECTION ----------------
# st.markdown("<div class='card'>", unsafe_allow_html=True)
# st.subheader("📌 Business Details")
# 
# business = st.text_input("🏪 Describe your business")
# budget = st.number_input("💰 Annual marketing budget (₹ / $)", min_value=0, step=1000)
# time = st.slider("⏱ Time available per week (hours)", 1, 15)
# goal = st.selectbox("🎯 Primary goal", ["Visibility", "Sales", "Expansion"])
# 
# platforms = st.multiselect(
#     "📱 Platforms you want to use",
#     ["Instagram", "WhatsApp", "YouTube", "Swiggy", "Zomato", "Urban Company",
#      "Etsy", "IndiaMART", "TradeIndia"]
# )
# st.markdown("</div>", unsafe_allow_html=True)
# 
# # ---------------- LOGIC (UNCHANGED) ----------------
# def analyze():
#     budget_level = "Low" if budget < 50000 else "Medium" if budget < 200000 else "High"
#     ready = budget_level != "Low" and time >= 4
#     st.session_state.ready = ready
# 
#     platform_text = ", ".join(platforms) if platforms else "one focused platform"
# 
#     st.session_state.analysis = f"""
# ### 📊 Business Analysis
# 
# **Business:** {business}
# **Budget:** {budget} ({budget_level})
# **Time Available:** {time} hrs/week
# **Goal:** {goal}
# 
# ---
# 
# ### 📱 Platform Direction
# Focus on **{platform_text}** with consistent, high-quality content.
# 
# ---
# 
# ### 🚦 Readiness Status
# {"✅ READY" if ready else "❌ NOT READY"}
# 
# {"### 💡 Budget Expansion Tips\n• Pre-orders & advance bookings\n• Referral incentives\n• Barter promotions\n• Reinvest early profits\n" if budget_level == "Low" else ""}
# """
# 
# def generate_plan():
#     st.session_state.plan = f"""
# ### 📅 7-Day Growth Plan
# 
# • 2 platform-specific posts
# • 1 engagement-focused post
# • Track inquiries and responses
# 
# Estimated effort: ~3 hrs/week
# """
# 
# def generate_pitch():
#     if st.session_state.ready:
#         st.session_state.pitch = """
# ### 🤝 Fundraising Strategy (Growth Stage)
# 
# • Approach micro-investors
# • Showcase engagement metrics
# • Partner with complementary businesses
# • Use Upsprout analysis as validation
# """
#     else:
#         st.session_state.pitch = """
# ### 🤝 Fundraising Strategy (Bootstrap Stage)
# 
# • Community selling & referrals
# • Pre-orders and advance payments
# • Barter-based collaborations
# • Local business partnerships
# """
# 
# # ---------------- ACTION CARDS ----------------
# st.subheader("🚀 Actions")
# 
# col1, col2, col3 = st.columns(3)
# 
# with col1:
#     st.markdown("""
#     <div class="action-card">
#         <div class="action-icon">🔍</div>
#         <div class="action-title">Analyze Business</div>
#     </div>
#     """, unsafe_allow_html=True)
#     if st.button("Analyze", key="analyze_btn"):
#         analyze()
# 
# with col2:
#     st.markdown("""
#     <div class="action-card">
#         <div class="action-icon">📈</div>
#         <div class="action-title">Growth Plan</div>
#     </div>
#     """, unsafe_allow_html=True)
#     if st.button("Plan", key="plan_btn"):
#         generate_plan()
# 
# with col3:
#     st.markdown("""
#     <div class="action-card">
#         <div class="action-icon">🤝</div>
#         <div class="action-title">Fundraising</div>
#     </div>
#     """, unsafe_allow_html=True)
#     if st.button("Fund", key="fund_btn"):
#         generate_pitch()
# 
# # ---------------- OUTPUT ----------------
# st.subheader("📤 Upsprout Output")
# 
# if st.session_state.analysis:
#     st.markdown("<div class='card'>", unsafe_allow_html=True)
#     st.markdown(st.session_state.analysis)
#     st.markdown("</div>", unsafe_allow_html=True)
# 
# if st.session_state.plan:
#     st.markdown("<div class='card'>", unsafe_allow_html=True)
#     st.markdown(st.session_state.plan)
#     st.markdown("</div>", unsafe_allow_html=True)
# 
# if st.session_state.pitch:
#     st.markdown("<div class='card'>", unsafe_allow_html=True)
#     st.markdown(st.session_state.pitch)
#     st.markdown("</div>", unsafe_allow_html=True)

!streamlit run app1.py &>/dev/null&

!./cloudflared-linux-amd64 tunnel --url http://localhost:8501

