# -*- coding: utf-8 -*-
"""datverse3ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OuAJts8LTMQUR3DTDLB7P2pbfjcyBFG0
"""

!pip install streamlit pyngrok

!streamlit run app1.py &>/dev/null&

!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared-linux-amd64

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# # ================= PAGE CONFIG =================
# st.set_page_config(
#     page_title="Upsprout 🌱",
#     page_icon="🤖",
#     layout="centered"
# )
# 
# # ================= STYLES =================
# st.markdown("""
# <style>
# [data-testid="stApp"] {
#     background: radial-gradient(circle at top left, #ECFEFF, #F0FDF4);
# }
# footer {visibility: hidden;}
# .card {
#     background: white;
#     padding: 1.8rem;
#     border-radius: 22px;
#     box-shadow: 0 14px 35px rgba(0,0,0,0.08);
#     margin-bottom: 1.6rem;
# }
# .hero {
#     background: linear-gradient(135deg, #34D399, #0EA5E9);
#     padding: 3rem;
#     border-radius: 28px;
#     color: white;
#     margin-bottom: 2rem;
# }
# .stButton > button {
#     background: linear-gradient(135deg, #0EA5E9, #22C55E);
#     color: white;
#     border-radius: 16px;
#     font-weight: 600;
# }
# h2, h3 { color: #15803D; }
# </style>
# """, unsafe_allow_html=True)
# 
# # ================= SESSION STATE =================
# defaults = {
#     "users": {},
#     "logged_in": False,
#     "current_user": "",
#     "analysis": "",
#     "plan": "",
#     "pitch": "",
#     "ready": False,
#     "score": 0
# }
# for k, v in defaults.items():
#     if k not in st.session_state:
#         st.session_state[k] = v
# 
# # =================================================
# # 🔐 LOGIN / REGISTER
# # =================================================
# if not st.session_state.logged_in:
#     st.markdown("<div class='card'>", unsafe_allow_html=True)
#     st.header("🔐 Welcome to Upsprout")
# 
#     mode = st.radio("Choose action", ["Login", "Register"])
#     username = st.text_input("Username")
#     password = st.text_input("Password", type="password")
# 
#     if st.button("Continue"):
#         if mode == "Register":
#             if not username or not password:
#                 st.warning("Please fill all fields.")
#             elif username in st.session_state.users:
#                 st.error("User already exists.")
#             else:
#                 st.session_state.users[username] = password
#                 st.success("Account created. Please login.")
#         else:
#             if st.session_state.users.get(username) == password:
#                 st.session_state.logged_in = True
#                 st.session_state.current_user = username
#                 st.rerun()
#             else:
#                 st.error("Invalid credentials")
# 
#     st.markdown("</div>", unsafe_allow_html=True)
# 
# # =================================================
# # 🌱 MAIN APP
# # =================================================
# else:
#     st.markdown(f"""
#     <div class="hero">
#         <h1>Upsprout 🌱</h1>
#         <p>Welcome <b>{st.session_state.current_user}</b> 👋<br>
#         AI-powered, resource-aware business growth assistant</p>
#     </div>
#     """, unsafe_allow_html=True)
# 
#     # ================= INPUT =================
#     st.markdown("<div class='card'>", unsafe_allow_html=True)
#     business = st.text_input("🏪 Describe your business")
#     budget = st.number_input("💰 Annual marketing budget", min_value=0, step=1000)
#     time = st.slider("⏱ Time available per week (hours)", 1, 15)
#     goal = st.selectbox("🎯 Primary goal", ["Visibility", "Sales", "Expansion"])
#     platforms = st.multiselect(
#         "📱 Platforms you want to use",
#         ["Instagram", "WhatsApp", "YouTube", "Swiggy", "Zomato",
#          "Etsy", "IndiaMART", "TradeIndia", "LinkedIn"]
#     )
#     st.markdown("</div>", unsafe_allow_html=True)
# 
#     # ================= HELPERS =================
#     def budget_level(b):
#         if b < 50000: return "Low"
#         if b < 200000: return "Medium"
#         return "High"
# 
#     def readiness(b_lvl, t):
#         score = (30 if b_lvl != "Low" else 10) + (40 if t >= 4 else 10) + 20
#         return score >= 70, score
# 
#     def business_key(text):
#         t = text.lower()
#         if any(k in t for k in ["restaurant","food","cafe","bakery"]): return "food"
#         if any(k in t for k in ["service","repair","salon","plumber"]): return "service"
#         if any(k in t for k in ["b2b","supplier","wholesale"]): return "b2b"
#         return "product"
# 
#     # ================= PLAYBOOK =================
#     PLAYBOOK = {
#         "food": {
#             "plan": [
#                 "Optimize menu photos & profile",
#                 "Take 3 food photos or reels",
#                 "Post best-selling dish",
#                 "Reply to comments & messages",
#                 "Post customer review",
#                 "Limited-time combo offer",
#                 "Review orders & engagement"
#             ],
#             "funding": {
#                 "bootstrap": "Reinvest daily profits into ingredients and ads",
#                 "crowd": "Local customers fund expansion through crowdfunding",
#                 "invest": "Angel investors for opening new outlets"
#             }
#         },
#         "product": {
#             "plan": [
#                 "Clarify product story",
#                 "Create lifestyle images",
#                 "Post product reel",
#                 "Answer customer questions",
#                 "Post testimonial",
#                 "Limited edition or bundle",
#                 "Review inquiries & sales"
#             ],
#             "funding": {
#                 "bootstrap": "Reinvest profits into inventory",
#                 "crowd": "Pre-orders and community crowdfunding",
#                 "invest": "Angel investors to scale production"
#             }
#         },
#         "service": {
#             "plan": [
#                 "List services clearly",
#                 "Capture before-after work",
#                 "Post service explanation",
#                 "Fast replies & follow-ups",
#                 "Post client testimonial",
#                 "Referral offer",
#                 "Review bookings"
#             ],
#             "funding": {
#                 "bootstrap": "Advance payments from clients",
#                 "crowd": "Referrals and partnerships",
#                 "invest": "Small service-focused investors"
#             }
#         },
#         "b2b": {
#             "plan": [
#                 "Finalize catalog & pricing",
#                 "Post professional overview",
#                 "Outreach to leads",
#                 "Follow up",
#                 "Share case study",
#                 "Bulk pricing offer",
#                 "Review inquiries"
#             ],
#             "funding": {
#                 "bootstrap": "Advance payments from clients",
#                 "crowd": "Usually not suitable",
#                 "invest": "Loans or invoice financing"
#             }
#         }
#     }
# 
#     # ================= ANALYZE =================
#     def analyze():
#         b_lvl = budget_level(budget)
#         ready, score = readiness(b_lvl, time)
#         st.session_state.ready = ready
#         st.session_state.score = score
#         key = business_key(business)
# 
#         confidence = min(95, score)
#         reasons = []
#         if b_lvl != "Low": reasons.append("sufficient budget")
#         if time >= 4: reasons.append("adequate time commitment")
#         reasons.append("focused growth goal")
# 
#         base = f"""
# ### 📊 Business Analysis
# **Business Type:** {key.title()}
# **Budget Level:** {b_lvl}
# **Time Available:** {time} hrs/week
# **Goal:** {goal}
# 
# ### 📱 Platforms
# {", ".join(platforms) if platforms else "Focus on one strong platform"}
# """
# 
#         if not ready:
#             st.session_state.analysis = base + f"""
# ---
# ### 🚦 Readiness Status: NOT READY ({score}/100)
# 
# ### 📉 Confidence Level
# **Confidence:** {confidence}%
# 
# **Why confidence is low:**
# • Limited time or budget
# • Inconsistent execution risk
# 
# **How to improve confidence:**
# • Increase effort to 4+ hrs/week
# • Use pre-orders or referrals to expand budget
# • Stay consistent for 2 weeks
# 
# Upsprout unlocks advanced insights once stability improves.
# """
#         else:
#             st.session_state.analysis = base + f"""
# ---
# ### 🚦 Readiness Status: READY ({score}/100)
# 
# ### ✅ AI Confidence
# **Confidence Level:** {confidence}%
# 
# **Why Upsprout is confident:**
# • {", ".join(reasons)}
# • Low-risk growth approach
# 
# ### ⚖ Trade-off Awareness
# • Faster growth → more effort required
# • Organic growth → safer but slower returns
# 
# ### 🧪 Suggested Experiment
# **Try:** 2 quality posts this week
# **Measure:** Inquiries & saves
# **Review:** After 7 days
# 
# Proceed with controlled scaling.
# """
# 
#     # ================= PLAN =================
#     def plan():
#         key = business_key(business)
#         days = PLAYBOOK[key]["plan"]
#         st.session_state.plan = "### 📅 7-Day Growth Plan\n\n"
#         for i, d in enumerate(days, 1):
#             st.session_state.plan += f"**Day {i}:** {d}\n\n"
# 
#     # ================= FUNDRAISING (ONLY SECTION CHANGED) =================
#     def fund():
#         key = business_key(business)
#         f = PLAYBOOK[key]["funding"]
# 
#         fund_score = 80 if st.session_state.ready else 45
#         fund_status = "READY" if st.session_state.ready else "NOT READY"
# 
#         checklist = [
#             "Clear explanation of the business offering",
#             "Basic customer proof (sales, inquiries, or reviews)",
#             "Consistent weekly activity",
#             "Clear plan for how funds will be used"
#         ]
# 
#         if st.session_state.ready:
#             st.session_state.pitch = f"""
# ### 💰 Fundraising Readiness Score
# **Score:** {fund_score}/100
# **Status:** {fund_status}
# 
# ---
# 
# ### ✅ Fundraising Preparation Checklist
# {"".join([f"- {c}\n" for c in checklist])}
# 
# ---
# 
# ### 🤝 Fundraising Pitch
# We are a growing **{key.title()} business** with steady customer interest.
# We are seeking funds to scale operations sustainably and improve reach.
# 
# ---
# 
# ### 🌱 Best Fundraising Paths
# **Bootstrapping:** {f['bootstrap']}
# • Safest option with full control
# 
# **Crowdfunding:** {f['crowd']}
# • Best if customers trust your brand
# 
# **Investors / Loans:** {f['invest']}
# • Faster growth but needs proof
# 
# ---
# 
# ### 🚀 How to Improve Fund Readiness
# • Track weekly sales and inquiries
# • Collect testimonials
# • Show 30-day consistency
# • Clearly explain fund usage
# 
# Upsprout recommends raising funds only with stability.
# """
#         else:
#             st.session_state.pitch = f"""
# ### 💰 Fundraising Readiness Score
# **Score:** {fund_score}/100
# **Status:** {fund_status}
# 
# ---
# 
# ### ✅ Fundraising Preparation Checklist
# {"".join([f"- {c}\n" for c in checklist])}
# 
# ---
# 
# ### 🤝 Fundraising Guidance (Early Stage)
# Raising funds too early may increase risk.
# 
# ---
# 
# ### 🌱 Safer Funding Paths
# **Bootstrapping:** {f['bootstrap']}
# • Reinvest small profits carefully
# 
# **Pre-orders / Referrals:**
# • Validate demand without external money
# 
# ---
# 
# ### 🚀 How to Improve Fund Readiness
# • Improve consistency
# • Build trust & reviews
# • Focus on one core offering
# 
# Upsprout unlocks advanced fundraising once stable.
# """
# 
#     # ================= ACTIONS =================
#     c1, c2, c3 = st.columns(3)
#     with c1:
#         if st.button("🔍 Analyze"): analyze()
#     with c2:
#         if st.button("📈 Growth Plan"): plan()
#     with c3:
#         if st.button("🤝 Fundraising"): fund()
# 
#     # ================= OUTPUT =================
#     st.header("📤 Upsprout Output")
#     for sec in ["analysis", "plan", "pitch"]:
#         if st.session_state[sec]:
#             st.markdown("<div class='card'>", unsafe_allow_html=True)
#             st.markdown(st.session_state[sec])
#             st.markdown("</div>", unsafe_allow_html=True)
# 
#     # ================= LOGOUT =================
#     if st.button("🚪 Logout"):
#         st.session_state.logged_in = False
#         st.session_state.current_user = ""
#         st.rerun()

!ls

!streamlit run app.py & ./cloudflared-linux-amd64 tunnel --url http://localhost:8501