# -*- coding: utf-8 -*-
"""datverse3ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OuAJts8LTMQUR3DTDLB7P2pbfjcyBFG0
"""

!pip install streamlit pyngrok

!streamlit run app1.py &>/dev/null&

!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared-linux-amd64

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# 
# # ================= PAGE CONFIG =================
# st.set_page_config(
#     page_title="Upsprout 🌱",
#     page_icon="🤖",
#     layout="centered"
# )
# 
# # ================= STYLES =================
# st.markdown("""
# <style>
# [data-testid="stApp"] {
#     background: radial-gradient(circle at top left, #ECFEFF, #F0FDF4);
# }
# footer {visibility: hidden;}
# .card {
#     background: white;
#     padding: 1.8rem;
#     border-radius: 22px;
#     box-shadow: 0 14px 35px rgba(0,0,0,0.08);
#     margin-bottom: 1.6rem;
# }
# .hero {
#     background: linear-gradient(135deg, #34D399, #0EA5E9);
#     padding: 3rem;
#     border-radius: 28px;
#     color: white;
#     margin-bottom: 2rem;
# }
# .stButton > button {
#     background: linear-gradient(135deg, #0EA5E9, #22C55E);
#     color: white;
#     border-radius: 16px;
#     font-weight: 600;
# }
# h2, h3 { color: #15803D; }
# .small { color:#555; font-size:14px; }
# </style>
# """, unsafe_allow_html=True)
# 
# # ================= SESSION STATE =================
# defaults = {
#     "users": {},
#     "logged_in": False,
#     "current_user": "",
#     "current_role": "",
#     "analysis": "",
#     "plan": "",
#     "pitch": "",
#     "ready": False,
#     "score": 0,
#     "investments": {},
#     "founder_data": {}
# }
# for k, v in defaults.items():
#     if k not in st.session_state:
#         st.session_state[k] = v
# 
# # =================================================
# # 🔐 LOGIN / REGISTER
# # =================================================
# if not st.session_state.logged_in:
#     st.markdown("<div class='card'>", unsafe_allow_html=True)
#     st.header("🔐 Welcome to Upsprout")
# 
#     mode = st.radio("Choose action", ["Login", "Register"])
#     username = st.text_input("Username")
#     password = st.text_input("Password", type="password")
# 
#     role = None
#     if mode == "Register":
#         role = st.selectbox("Register as", ["Founder", "Investor"])
# 
#     if st.button("Continue"):
#         if mode == "Register":
#             if not username or not password:
#                 st.warning("Fill all fields.")
#             elif username in st.session_state.users:
#                 st.error("User exists.")
#             else:
#                 st.session_state.users[username] = {
#                     "password": password,
#                     "role": role
#                 }
#                 st.success("Account created. Login now.")
#         else:
#             user = st.session_state.users.get(username)
#             if user and user["password"] == password:
#                 st.session_state.logged_in = True
#                 st.session_state.current_user = username
#                 st.session_state.current_role = user["role"]
#                 st.rerun()
#             else:
#                 st.error("Invalid credentials")
#     st.stop()
# 
# # ================= SIDEBAR =================
# st.sidebar.title("🌱 Upsprout")
# page = st.sidebar.radio(
#     "Navigate",
#     ["📊 Dashboard", "🔍 Analysis", "📅 Growth Plan", "🤝 Fundraising"]
# )
# 
# if st.sidebar.button("🚪 Logout"):
#     st.session_state.logged_in = False
#     st.session_state.current_user = ""
#     st.session_state.current_role = ""
#     st.rerun()
# 
# # ================= HERO =================
# st.markdown(f"""
# <div class="hero">
#     <h1>Upsprout 🌱</h1>
#     <p>Welcome <b>{st.session_state.current_user}</b> ({st.session_state.current_role}) 👋<br>
#     Explainable AI for business growth & investing</p>
# </div>
# """, unsafe_allow_html=True)
# 
# # ================= HELPERS =================
# def budget_level(b):
#     if b < 50000: return ("Low", 10)
#     if b < 200000: return ("Medium", 20)
#     return ("High", 30)
# 
# def business_type(text):
#     t = text.lower()
#     if any(k in t for k in ["restaurant","food","cafe","bakery"]): return ("Food", -5)
#     if any(k in t for k in ["service","repair","salon"]): return ("Service", -3)
#     if any(k in t for k in ["b2b","supplier","wholesale"]): return ("B2B", -8)
#     return ("Product", -6)
# 
# def readiness_score(budget, time, goal, business):
#     lvl, b_score = budget_level(budget)
#     time_score = 40 if time >= 4 else 15
#     goal_score = 20
#     btype, risk_penalty = business_type(business)
#     total = b_score + time_score + goal_score + 10
#     confidence = max(0, min(95, total + risk_penalty))
#     return lvl, total, confidence, btype
# 
# # ================= INPUT (FOUNDERS ONLY) =================
# if st.session_state.current_role == "Founder":
#     st.markdown("<div class='card'>", unsafe_allow_html=True)
#     business = st.text_input("🏪 Describe your business")
#     budget = st.number_input("💰 Annual marketing budget", min_value=0, step=1000)
#     time = st.slider("⏱ Time per week (hours)", 1, 15)
#     goal = st.selectbox("🎯 Primary goal", ["Visibility", "Sales", "Expansion"])
#     st.markdown("</div>", unsafe_allow_html=True)
# 
#     # ✅ FIX: Do NOT overwrite founder data on reruns
#     if business.strip() != "":
#         st.session_state.founder_data.setdefault(
#             st.session_state.current_user,
#             {
#                 "business": business,
#                 "budget": budget,
#                 "time": time,
#                 "goal": goal
#             }
#         )
# 
# # ================= DASHBOARD =================
# if page == "📊 Dashboard":
#     st.markdown("<div class='card'>", unsafe_allow_html=True)
# 
#     if st.session_state.current_role == "Founder":
#         st.subheader("🤝 Investor Interest")
#         investors = st.session_state.investments.get(st.session_state.current_user, [])
#         if investors:
#             for i in investors:
#                 st.success(f"💰 {i} showed interest")
#         else:
#             st.info("No investors yet.")
# 
#     else:
#         st.subheader("🌱 Founder Opportunities")
# 
#         table_rows = []
# 
#         for founder, data in st.session_state.founder_data.items():
#             lvl, score, confidence, btype = readiness_score(
#                 data["budget"], data["time"], data["goal"], data["business"]
#             )
# 
#             table_rows.append({
#                 "Founder": founder,
#                 "Business Type": btype,
#                 "Budget Level": lvl,
#                 "Time (hrs/week)": data["time"],
#                 "Readiness Score": score,
#                 "Confidence (%)": confidence,
#                 "Risk Category": "Low" if confidence > 70 else "Medium",
#                 "Suggested Investor": "Patient Angel" if confidence > 65 else "Mentor-backed"
#             })
# 
#         if table_rows:
#             st.subheader("📊 Investor Comparison Table")
#             st.dataframe(pd.DataFrame(table_rows), use_container_width=True)
# 
#         st.markdown("<hr>", unsafe_allow_html=True)
# 
#         for founder, data in st.session_state.founder_data.items():
#             lvl, score, confidence, btype = readiness_score(
#                 data["budget"], data["time"], data["goal"], data["business"]
#             )
# 
#             st.markdown("<div class='card'>", unsafe_allow_html=True)
#             st.markdown(f"""
# ### 🏪 {founder} — {btype} Business
# 
# **Readiness Score:** {score}/100
# **Confidence:** {confidence}%
# 
# **Why Upsprout is confident:**
# • Budget sufficiency ({lvl})
# • Time commitment ({data['time']} hrs/week)
# • {btype}-sector risk adjustment applied
# 
# **Trade-offs Identified:**
# • Growth speed vs stability
# • Sector-specific demand volatility
# """)
# 
#             c1, c2 = st.columns(2)
#             with c1:
#                 if st.button("💰 Invest", key=f"inv_{founder}"):
#                     st.session_state.investments.setdefault(founder, []).append(
#                         st.session_state.current_user
#                     )
#                     st.success("Investment interest recorded")
#             with c2:
#                 st.button("🤝 Collaborate", key=f"col_{founder}")
# 
#             st.markdown("</div>", unsafe_allow_html=True)
# 
#     st.markdown("</div>", unsafe_allow_html=True)

!ls

!streamlit run app.py & ./cloudflared-linux-amd64 tunnel --url http://localhost:8501